name: mental_wellness_app_fixed3
description: App de Bienestar Emocional con Flutter + Supabase + Gemini
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.3.0
  font_awesome_flutter: ^10.7.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  file_picker: ^8.0.3

  http: ^1.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1

  # Backend & auth
  supabase_flutter: ^2.5.0

  # Google AI (Gemini)
  google_generative_ai: ^0.4.7

  # Permisos / utilidades
  permission_handler: ^11.4.0
  url_launcher: ^6.3.0

  # Audio / voz a texto
  speech_to_text: ^7.3.0

  # Gráficas de evolución
  fl_chart: ^0.68.0

  mime: any
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.5.4
  freezed: ^2.5.8
  json_serializable: ^6.9.5

  # Generador de íconos
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
